"""setup_vector_schema

Revision ID: e6613535abd2
Revises: e9c2f68eed9c
Create Date: 2026-03-31 16:51:43.366039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e6613535abd2'
down_revision: Union[str, None] = 'e9c2f68eed9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Add similarity search function
    op.execute("""
    CREATE OR REPLACE FUNCTION match_documents (
      query_embedding vector(384),
      filter jsonb default '{}'
    ) RETURNS TABLE (
      id uuid,
      content text,
      metadata jsonb,
      similarity float
    ) LANGUAGE plpgsql AS $$
    BEGIN
      RETURN QUERY
      SELECT
        documents.id,
        documents.content,
        documents.metadata,
        1 - (documents.embedding <=> query_embedding) AS similarity
      FROM documents
      WHERE documents.metadata @> filter
      ORDER BY documents.embedding <=> query_embedding;
    END;
    $$;
    """)


def downgrade() -> None:
    # Drop function first
    op.execute("DROP FUNCTION IF EXISTS match_documents(vector, jsonb)")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documents')
    # ### end Alembic commands ###
